application: guuksnow
version: 4
runtime: python
api_version: 1

handlers:
- url: /styles
  static_dir: static/styles

- url: /images
  static_dir: static/images

- url: /js
  static_dir: static/js

- url: /admin/.*
  script: admin.py

- url: /services/.*
  script: services.py
  login: admin

- url: .*
  script: main.py
